global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 0.2
   static_map: true
   rolling_window: false
   resolution: 0.025
   transform_tolerance: 2.0
   map_type: costmap

   inflation_radius: 0.05
   cost_scaling_factor: 0.55
