local_costmap:
   global_frame: odom 
   robot_base_frame: base_link
   update_frequency: 3.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 1.5
   height: 1.5
   resolution: 0.025
   transform_tolerance: 2.0

   inflation_radius: 0.05
   cost_scaling_factor: 0.55
