
#---standard pioneer footprint---
#---(in meters)---
#robot_radius: 0.075
footprint: [[-0.045, 0.06], [0.105, 0.06], [0.105, -0.06], [-0.045, -0.06]]
footprint_padding: 0.00

transform_tolerance: 2.0
map_type: costmap

always_send_full_costmap: true  #true

obstacle_layer:
 enabled: true
 obstacle_range: 1.5
 raytrace_range: 2.5
 inflation_radius: 0.05
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

static_layer:
  enabled:              true
  map_topic:            "map"
