#robot_radius: 0.075 # 机器人半径

obstacle_range: 1.5 # 规避障碍的范围
raytrace_range: 2.5 # 探测障碍的范围
footprint: [[-0.045, 0.06], [0.105, 0.06], [0.105, -0.06], [-0.045, -0.06]]
footprint_padding: 0.00
footprint_inflation: 0.025 # 机器人膨胀层

max_obstacle_height: 0.8

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
